name: Resuable workflow
on:
  # To reuse this workflow in other workflow jobs we need this 
  # in built event trigger
  workflow_call:
    inputs: # reserved keyword to tell about the inputs we get
      input-arg1: # any name we want to call our argument we receive from calling job
      # this is the same name we need to use from the workflow > job from where we initiate it
        description: "Tells about the input-arg1"
        type: string
        default: "Default to something"
        required: true # while using this workflow we need to pass this input
      input-arg2:
        description: "Tells about input-arg2"
        type: string
        required: false
        default: 'anything'
    secrets: # same as inputs we can get some secrets
    # secrets is reserved keyword
      secret1: # any name we want to assign our secret
      # this is same identifier we use for passing secrtes from calling jobs
        required: true # makes this secret mandatory
        # we can provide default values
    outputs: #To return some output from this Reusable workflows to the called job
      reusable-workflow-output-var1: # any name we want to hold the output from this workflow
        description: Tells about this output variable
        value: ${{ jobs.simple-job.outputs.job-output-var }}
        # jobs is inbuilt context object can be used only in reusable workflows
        # get the any output value from the jobs of this workflow and assign here
  workflow_dispatch:
jobs:
  simple-job:
    runs-on: ubuntu-latest
    outputs:
      #job level output by reading results from steps using step id
      job-output-var: ${{ steps.step-id-1.outputs.step-output-var }}
    steps:
      - name: Echo something
        run: echo "Executed Reusable Workflow"
      - name: Echo arg1
        run: echo "${{ inputs.input-arg1 }}"
        # inputs is inbuilt context which holds the inputs passed while using this workflow
      - name: Echo arg2
        run: echo "${{ inputs.input-arg2 }}"
      - name: Echo secrets
        run: echo "${{ secrets.secret1 }}"
        # secrets is inbuilt context which provides list of secrets passed
      - name: Return some Output
        id: step-id-1
        # outputs some result from this step and assign to step level variable
        run: echo 'step-output-var={'output from reusable workflow'}' >> $GITHUB_OUTPUT