name: Using Custom actions - Javascript
on:
  workflow_dispatch:
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Custom Action to Print Hello world from Javascript
        id: custom-javascript-action-call
        uses: ./.github/custom-actions/javascript-action