name: Workflow with Expressions and Context
on:
  workflow_dispatch:
jobs:
  expression-github:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Github context with expression # github is inbuilt context object
        run: echo "${{ toJSON(github) }}" # ${{ }} -> is the syntax for writing expression
