name: Trigger - Activity Types
on:
  pull_request: #Trigger 1
    types:
      - opened
      - edited
    branches:
      - main # filters the PR created for these branches only
  workflow_dispatch: #Trigger 2
  push:
    branches:
      - main
      - dev*
    paths:
      - ".github/*" # changes done to these only files from the specified branches only
jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Echo
        run: echo "This gets triggred on PullRequest - opened or edited"
